version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: sulwork_cafe_db
    environment:
      POSTGRES_DB: sulwork_cafe
      POSTGRES_USER: sulwork
      POSTGRES_PASSWORD: sulwork
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: sulwork_cafe_app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: