spring:
  mvc:
    cors:
      mappings:
        "[/api/**]":
          allowed-origins: "http://localhost:4000, https://sulwork-cafe-frontend-production.up.railway.app"
          allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
          allowed-headers: "*"
          exposed-headers: "Location"
          allow-credentials: false
          max-age: 3600
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.lob.non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baseline-version: ${FLYWAY_BASELINE_VERSION:0}

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui.path: /swagger
  api-docs.path: /v3/api-docs